### ISSUE TITLE
First time start of PMOD NAV doesn't work

### ISSUE THREAD

**Issue by peerst** [grisp/grisp#29] opened 2018-05-30 18:10 UTC
The who am I register is wrong the first time its read.  Need some investigation if we are
using it wrong or its just broken.  

Since we check for it it crashes on first start

**Comment by nextl00p** [comment] 2018-06-05 12:30
Is this a duplicate of #11

**Comment by eproxus** [comment] 2018-06-06 12:38
@nextl00p Yes, closing.

**Closed by eproxus** 2018-06-06 12:38 UTC
Labels: bug, duplicate
